
(define kernel_files '(hydro_A implicit_particle_mover type3_georel inner_split_pass inner_split_pass_slab inner_split_pass_slab_midp geo_particle_iter_mass geo_particle_iter rel_particle_iter geoslab_relng_2nd_particle_iter geoslab_relng_2nd_cpp_particle_iter yeefdtd stencil mergefields miniblas general_partial_sort move_back particle_iter mur_abc dmbihamt dm8x8 dm geo_yeefdtd_rect geo_yeefdtd))
;(define kernel_files '(hydro_A))
